Add and use Debian-trixie-live.yaml example
Port `Debian-bullseye-live.yaml` to the latest Debian stable version and
use this newer config for the README.md and the system test.

iputils 3:20240117-1 stopped falling back to setuid binaries for raw
socket access. So `ping` has no xattr set any more. Use `clockdiff`
(which has `cap_sys_nice` set since 3:20240905-1) as test case.

diff --git a/system-testing b/system-testing
--- a/system-testing
+++ b/system-testing
@@ -42,29 +42,27 @@ test_example1() {
 
 test_example2() {
     header "Example 2: Debian live system"
-    sed '/  - upload ~/d' "$examples_dir/Debian-bullseye-live.yaml" > Debian-bullseye-live.yaml
+    sed '/  - upload ~/d' "$examples_dir/Debian-trixie-live.yaml" > Debian-trixie-live.yaml
     if test "$DEB_HOST_ARCH" != amd64; then
         # Use host architecture to avoid testing building for foreign architecture
         case "$DEB_HOST_ARCH" in
             arm64) kernel="linux-image-cloud-arm64" ;;
             armel) kernel="linux-image-rpi" ;;
             armhf) kernel="linux-image-armmp-lpae" ;;
-            i386) kernel="linux-image-686-pae" ;;
-            mips64el|mipsel) kernel="linux-image-octeon" ;;
             ppc64el) kernel="linux-image-powerpc64le" ;;
             *) kernel="linux-image-${DEB_HOST_ARCH}" ;;
         esac
-        sed -i "s/linux-image-cloud-amd64/${kernel}/" Debian-bullseye-live.yaml
-        sed -i "s/amd64/${DEB_HOST_ARCH}/" Debian-bullseye-live.yaml
+        sed -i "s/linux-image-cloud-amd64/${kernel}/" Debian-trixie-live.yaml
+        sed -i "s/amd64/${DEB_HOST_ARCH}/" Debian-trixie-live.yaml
     fi
-    "$bdebstrap_binary" -v -c Debian-bullseye-live.yaml --packages iputils-ping --name example2 --mode root
+    "$bdebstrap_binary" -v -c Debian-trixie-live.yaml --packages iputils-clockdiff --name example2 --mode root
     check_existing example2 config.yaml initrd.img manifest root.squashfs vmlinuz
-    xattr=$(rdsquashfs -x /bin/ping example2/root.squashfs)
+    xattr=$(rdsquashfs -x /usr/bin/clockdiff example2/root.squashfs)
     if test -z "$xattr"; then
-        echo "Error: /bin/ping from example2/root.squashfs lacks security xattrs!" >&2
+        echo "Error: /usr/bin/clockdiff from example2/root.squashfs lacks security xattrs!" >&2
         return 1
     else
-        echo "Info: /bin/ping has xattrs: $xattr"
+        echo "Info: /usr/bin/clockdiff has xattrs: $xattr"
     fi
     rm -r example2
 }
